Update CI

diff --git a/.github/workflows/testing.yml b/.github/workflows/testing.yml
--- a/.github/workflows/testing.yml
+++ b/.github/workflows/testing.yml
@@ -20,7 +20,7 @@ jobs:
       matrix:
         include:
           # By default only linux has a release job.
-          # This is to keep within the 5GB cache limit as rust can use a lot of space!
+          # This is to keep within the 10GB cache limit as rust can use a lot of space!
           # There are also more limits here but I dont think there is much risk of hitting them: https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#usage-limits
           - name: LinuxRelease
             runner: ubuntu-latest
@@ -58,3 +58,13 @@ jobs:
       run: cargo hack --feature-powerset clippy --all-targets --locked ${{ matrix.cargo_profile }} -- -D warnings
     - name: Ensure that tests pass under every possible combination of features
       run: cargo hack --feature-powerset test ${{ matrix.cargo_profile }}
+    - name: Ensure that tests did not create or modify any files that arent .gitignore'd
+      # This is important because we are checking in the Cargo.lock file.
+      # We want to fail CI if the Cargo.toml changed without including the corresponding Cargo.lock changes.
+      # Its also just generally nice to ensure your tests dont leave around unexpected files.
+      shell: bash
+      run: |
+        if [ -n "$(git status --porcelain)" ]; then
+          git status
+          exit 1
+        fi
